import { stationAction, skillChoice } from "../event/event-schema.js";

export const FALLBACK_ACTIONS = Object.freeze({
  captain: stationAction({ id: "captain.coordinate-crew", station: "captain", name: "Coordinate the Crew", description: "Read the crisis, call priorities, and keep the bridge moving as one crew.", skills: [skillChoice({ id: "captain.coordinate.diplomacy", label: "Diplomacy", skill: "diplomacy", dc: 18 }), skillChoice({ id: "captain.coordinate.intimidation", label: "Intimidation", skill: "intimidation", dc: 18 })], tags: ["fallback", "command", "teamwork"] }),
  engineer: stationAction({ id: "engineer.stabilize-systems", station: "engineer", name: "Stabilize Systems", description: "Keep the Arkengine and ship systems inside safe operating limits while the crisis unfolds.", skills: [skillChoice({ id: "engineer.stabilize.crafting", label: "Crafting", skill: "crafting", dc: 18 }), skillChoice({ id: "engineer.stabilize.arcana", label: "Arcana", skill: "arcana", dc: 18 })], tags: ["fallback", "arkengine", "strain"] }),
  navigator: stationAction({ id: "navigator.correct-course", station: "navigator", name: "Correct Course", description: "Find the safest viable line through the immediate danger and keep the ship on it.", skills: [skillChoice({ id: "navigator.correct.survival", label: "Survival", skill: "survival", dc: 18 }), skillChoice({ id: "navigator.correct.nature", label: "Nature", skill: "nature", dc: 18 })], tags: ["fallback", "navigation", "helm"] }),
  battlewatch: stationAction({ id: "battlewatch.scan-threats", station: "battlewatch", name: "Scan for Threats", description: "Track the most immediate danger and feed the crew the warning they need before it becomes a disaster.", skills: [skillChoice({ id: "battlewatch.scan.perception", label: "Perception", skill: "perception", dc: 18 }), skillChoice({ id: "battlewatch.scan.society", label: "Society", skill: "society", dc: 18 })], tags: ["fallback", "detection", "hazard", "weapons"] }),
  veilwarden: stationAction({ id: "veilwarden.reinforce-veil", station: "veilwarden", name: "Reinforce the Veil", description: "Steady the Lifeveil and keep hostile aetheric forces from reaching the crew.", skills: [skillChoice({ id: "veilwarden.reinforce.religion", label: "Religion", skill: "religion", dc: 18 }), skillChoice({ id: "veilwarden.reinforce.occultism", label: "Occultism", skill: "occultism", dc: 18 })], tags: ["fallback", "lifeveil", "defense"] })
});
