import { component, COMPONENT_TYPES } from "../ship/component-rules.js";
const C=["arkengine-chamber","helm","crew-quarters","galley-and-mess","cargo-hold","officer-wardroom"];
const CORE_MASTERY=Object.freeze({
 captain:["captain-carry-the-deed","captain-set-the-pace","captain-not-like-this"],
 engineer:["engineer-redline-the-arkengine","engineer-keep-her-breathing","engineer-crosswire-the-systems"],
 navigator:["navigator-impossible-passage","navigator-find-another-way","navigator-read-the-current"],
 battlewatch:["battlewatch-call-the-true-opening","battlewatch-nothing-surprises-me","battlewatch-exploit-the-break"],
 veilwarden:["veilwarden-stand-between","veilwarden-seal-the-impossible","veilwarden-sanctuary"]
});
const coreUnlocks=()=>({stations:Object.fromEntries(Object.entries(CORE_MASTERY).map(([station,masteries])=>[station,{masteries:[...masteries]}]))});
const h=(id,name,description,tier,tags,baseStats,preferredArkengine,allowedArkengines,districtScale=false)=>component({id,name,type:COMPONENT_TYPES.HULL,description,tags:["core-hull",...tags],traits:["core-hull",...tags],data:{tier,baseStats,coreRooms:C,districtScale,preferredArkengine,allowedArkengines},unlocks:coreUnlocks()});
const m=(fore=[0,"small"],port=[0,"small"],starboard=[0,"small"],aft=[0,"small"])=>({fore:{count:fore[0],maxSize:fore[1]},port:{count:port[0],maxSize:port[1]},starboard:{count:starboard[0],maxSize:starboard[1]},aft:{count:aft[0],maxSize:aft[1]}});
const s=(armorClass,hullIntegrity,lifeveilCapacity,strainCapacity,cargoCapacity,detection,combatSpeed,maneuverability,roomCapacity,crew,weaponMounts,physicalResistances)=>({armorClass,hullIntegrity,lifeveilCapacity,strainCapacity,cargoCapacity,detection,combatSpeed,maneuverability,roomCapacity,shipModCapacity:roomCapacity,arkengineModCapacity:0,crew,weaponMounts,physicalResistances});
export const HULLS=Object.freeze(Object.fromEntries([
 h("void-skiff","Void Skiff","Tiny fast craft, scout, launch, personal voidboat.",1,["tiny","fast","scout"],s(18,60,20,4,8,2,8,3,1,{minimum:1,recommended:3,maximum:6},m([1,"small"]),{bludgeoning:0,piercing:0,slashing:0}),"emberwake-sparkdrive",["emberwake-sparkdrive","lanterncoil-arkengine"]),
 h("sloop","Sloop","Small adventuring ship, courier, scout, light raider.",1,["small","courier","scout"],s(18,90,30,6,16,3,7,3,2,{minimum:3,recommended:6,maximum:12},m([1,"small"],[1,"small"],[1,"small"]),{bludgeoning:1,piercing:1,slashing:0}),"lanterncoil-arkengine",["emberwake-sparkdrive","lanterncoil-arkengine","tidewake-arkengine"]),
 h("cutter","Cutter","Durable small ship, patrol craft, starter party vessel.",1,["small","durable","patrol"],s(17,120,40,8,28,3,6,2,3,{minimum:4,recommended:10,maximum:20},m([1,"medium"],[1,"small"],[1,"small"],[1,"small"]),{bludgeoning:2,piercing:1,slashing:1}),"lanterncoil-arkengine",["emberwake-sparkdrive","lanterncoil-arkengine","tidewake-arkengine"]),
 h("brigantine","Brigantine","Flexible home ship, adventuring workhorse.",2,["flexible","workhorse"],s(17,160,55,10,40,4,5,2,4,{minimum:5,recommended:14,maximum:32},m([1,"medium"],[2,"small"],[2,"small"],[1,"small"]),{bludgeoning:2,piercing:2,slashing:1}),"tidewake-arkengine",["lanterncoil-arkengine","tidewake-arkengine","iron-choir-engine"]),
 h("frigate","Frigate","Combat-focused escort and warship.",2,["escort","warship"],s(18,190,50,11,34,5,6,2,4,{minimum:6,recommended:24,maximum:60},m([1,"medium"],[2,"medium"],[2,"medium"],[1,"small"]),{bludgeoning:3,piercing:2,slashing:2}),"iron-choir-engine",["tidewake-arkengine","iron-choir-engine","furnaceheart-drive"]),
 h("galleon","Galleon","Heavy cargo, logistics, colony support, merchant flagship.",3,["heavy-cargo","logistics","merchant"],s(15,260,75,13,90,3,3,1,6,{minimum:10,recommended:45,maximum:120},m([1,"medium"],[3,"medium"],[3,"medium"],[1,"medium"]),{bludgeoning:4,piercing:3,slashing:3}),"furnaceheart-drive",["iron-choir-engine","furnaceheart-drive","voidbreaker-arkengine"]),
 h("hammerhead","Hammerhead","Frontal assault, ramship, siege breaker.",3,["assault","ramship","siege"],s(16,240,60,14,55,3,4,1,5,{minimum:8,recommended:35,maximum:90},m([1,"large"],[2,"medium"],[2,"medium"],[1,"small"]),{bludgeoning:5,piercing:4,slashing:3}),"voidbreaker-arkengine",["furnaceheart-drive","voidbreaker-arkengine","deepwake-veil-engine"]),
 h("arkcruiser","Arkcruiser","Long-range capital cruiser and campaign flagship.",4,["capital","long-range","flagship"],s(15,310,95,16,110,5,3,1,7,{minimum:12,recommended:70,maximum:180},m([1,"medium"],[3,"medium"],[3,"medium"],[2,"small"]),{bludgeoning:4,piercing:4,slashing:3}),"deepwake-veil-engine",["voidbreaker-arkengine","deepwake-veil-engine","crownfire-arkengine"]),
 h("dread-caravel","Dread Caravel","Elite warship and hunter-killer capital vessel.",4,["elite","warship","hunter-killer"],s(17,300,80,17,70,6,4,1,6,{minimum:14,recommended:90,maximum:240},m([1,"large"],[3,"medium"],[3,"medium"],[1,"medium"]),{bludgeoning:5,piercing:4,slashing:4}),"crownfire-arkengine",["deepwake-veil-engine","crownfire-arkengine","sanctum-choir-core"]),
 h("cathedral-ship","Cathedral Ship","Lifeveil fortress, religious vessel, ark sanctuary, support flagship.",5,["lifeveil","sanctuary","support-flagship"],s(14,280,120,15,75,6,2,1,7,{minimum:12,recommended:80,maximum:220},m([1,"medium"],[2,"medium"],[2,"medium"],[1,"medium"]),{bludgeoning:3,piercing:3,slashing:3}),"sanctum-choir-core",["crownfire-arkengine","sanctum-choir-core","worldbinder-arkengine"]),
 h("leviathan-class-platform","Leviathan Class Platform","Moving district/civilization, not a normal ship.",5,["leviathan","district-scale","civilization"],s(12,500,180,22,250,7,1,1,null,{minimum:50,recommended:300,maximum:1000},m([2,"large"],[4,"large"],[4,"large"],[2,"large"]),{bludgeoning:6,piercing:6,slashing:5}),"leviathan-heart-core",["leviathan-heart-core"],true)
].map(x=>[x.id,x])));
